language: php

php:
  - 7.0
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
#    - ILLUMINATE_VERSION="5.3.*" ORCHESTRA_VERSION="3.3.*" PHPUNIT_VERSION="5.7.*" COMPOSER_FLAGS="--prefer-lowest"
#    - ILLUMINATE_VERSION="5.3.*" ORCHESTRA_VERSION="3.3.*" PHPUNIT_VERSION="5.7.*" COMPOSER_FLAGS="--prefer-stable"
    - ILLUMINATE_VERSION="5.4.*" ORCHESTRA_VERSION="^3.4.2" PHPUNIT_VERSION="6.*" COMPOSER_FLAGS="--prefer-lowest"
    - ILLUMINATE_VERSION="5.4.*" ORCHESTRA_VERSION="^3.4.2" PHPUNIT_VERSION="6.*" COMPOSER_FLAGS="--prefer-stable"
#    - ILLUMINATE_VERSION="dev-master" ORCHESTRA_VERSION="dev-master" PHPUNIT_VERSION="6.*" COMPOSER_FLAGS="--prefer-lowest"
#    - ILLUMINATE_VERSION="dev-master" ORCHESTRA_VERSION="dev-master" PHPUNIT_VERSION="6.*"

matrix:
  allow_failures:
    - php: nightly
    - env: ILLUMINATE_VERSION="dev-master" ORCHESTRA_VERSION="dev-master" PHPUNIT_VERSION="6.*" COMPOSER_FLAGS="--prefer-lowest"
    - env: ILLUMINATE_VERSION="dev-master" ORCHESTRA_VERSION="dev-master" PHPUNIT_VERSION="6.*"
  fast_finish: true

before_install:
  - travis_retry composer self-update
  - composer require illuminate/database=${ILLUMINATE_VERSION} --no-update
  - composer require illuminate/support=${ILLUMINATE_VERSION} --no-update
  - composer require orchestra/testbench=${ORCHESTRA_VERSION} --dev --no-update
  - composer require phpunit/phpunit=${PHPUNIT_VERSION} --dev --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_failure: change
    on_success: never
